POST http://localhost:8080/api/v1/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="input.txt"

// The 'input.txt' file will be uploaded
< /tmp/input.txt
--boundary--
